### ISSUE TITLE
almost infinite loop

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#2312] opened 2018-10-26 07:04 UTC
## User Report
take several time to reach this question

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1450597248995390120.jpg)
## Device Info
```
Time Stamp: 2018-10-26T07:03:27 UTC
App Version: 0.5.0 (61)
Install Source: Unknown
Android Version: 8.1.0 (27)
Device Manufacturer: BQ
Device Model: AQUARIS X PRO
Display Resolution: 1920x1080
Display Density (Actual): 408dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by ifoche** [comment] 2018-10-26 07:11
duplicate of #2309

**Closed as completed by ifoche** 2018-10-26 07:11 UTC
Labels: duplicate
